### ISSUE TITLE
Purge UPS Templates and refactor corresponding features

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2783]
Removes / reverts
- [x] #2680 : Remove UPS Templates from LDAP / JSON configuration
- [x] #2688 : Remove [List UPS Templates](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/CONFIG-RS/listUPSTemplates) service
- [x] #2755 : Remove UI format `dcmUPSTemplateID`

Refactors usage of template in following services : 
- Replace `upsTemplateID` in path parameter with SOP Instance UID of UPS Template Workitem (to search for the UPS record in DB and using its attributes in creation of new workitems). 
  - [x] #2754 : Replace current `Create UPS On Cancel` configuration showing configured UPS Templates dropdown to a text field requiring user to enter the UPS Instance UID. 
  - [x] #2689 : Refactor [Create Workitems for local Studies specified in CSV](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemsLocalStudiesCSV) 
  - [x] #2690 : Refactor [Create Workitems for external Studies specified in CSV](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemsExternalStudiesCSV) 
- Replace `upsTemplateID` in path parameter (implemented in #2694 and #2695) with UPS Template Workitem attributes sent in request payload.
  - [x] #2694 Local matching entities
    - [Create workitems for local matching studies](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemsForLocalMatchingStudy) 
    - [Create Workitem for local matching Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForLocalMatchingSeriesOfStudy) 
    - [Create Workitem for local matching Instances of Series](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForLocalMatchingInstancesOfSeries)
  - [x] #2695 External matching entities
    - [Create Workitems for external matching Studies](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemsForExternalMatchingStudies) 
    - [Create Workitem for external matching Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForExternalMatchingSeries) 
    - [Create Workitem for external matching Instances of Series](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForExternalMatchingInstancesOfSeries)
    - [Create Workitems for external matching Studies queried from C-FIND SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemsForExternalMatchingStudies2)
    - [Create Workitem for external matching Series of Study queried from C-FIND SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForExternalMatchingSeriesOfStudy2) 
    - [Create Workitem for external matching Instances of Series queried from C-FIND SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/CreateWorkitemForExternalMatchingInstancesOfSeries2)

- [x] #2710 : Revert all earlier changes done in UI. Reopen the same issue and update it to reflect above changes

- [ ] Update [Unified Procedure Step (UPS) Processed Features](https://github.com/dcm4che/dcm4chee-arc-light/wiki/HowTos#unified-procedure-step-ups-processed-features) wiki to reflect above changes
