### ISSUE TITLE
Support IHE SWF Scheduled Workflow Multiple Identity Resolution option

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2964]
Support IHE SWF Scheduled Workflow Multiple Identity Resolution option according [IHE RAD Technical Framework Supplement: Multiple Image Manager/Archive (MIMA)](https://ihe.net/Technical_Framework/upload/IHE_RAD_Suppl_MIMA.pdf) as actor
- Image Manager/Archive 
- Performed Procedure Step Manager

Particularly
- [x] Supplement received Composite Objects with Issuer Of Patient ID and other attributes from configuration #888
- [x] Supplement received Modality Performed Procedure Steps with Issuer Of Patient ID and other attributes from configuration #889
- [ ] C-FIND SCP: Optionally nullify Accession Number in returned C-FIND RSP dependent on Issuer of Accession Number #2956
- [ ] QIDO-RS: Optionally nullify Accession Number in response dependent on Issuer of Accession Number #2957
- [ ] C-STORE SCU: Optionally nullify Accession Number in retrieved/exported Composite Objects dependent on Issuer of Accession Number #2958
- [ ] WADO-RS/URI: Optionally nullify Accession Number in responses dependent on Issuer of Accession Number #2959
- [ ] C-FIND SCP: Optionally query external Patient Identifier Cross-Reference Managers for corresponding patient identifiers  #2960
- [ ] QIDO-RS: Optionally query external Patient Identifier Cross-Reference Managers for corresponding patient identifiers #2961
- [ ] C-STORE SCU: Optionally query external Patient Identifier Cross-Reference Managers for corresponding patient identifiers #2962
- [ ] WADO-RS/URI: Optionally query external Patient Identifier Cross-Reference Managers for corresponding patient identifiers #2963
