### ISSUE TITLE
UI Navigation DIFF: Provide operations for particular/all studies with detected differences

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3024]
Includes:
- [ ] UI Navigation DIFF: Widget to retrieve a particular study #2976 
- [ ] UI Navigation DIFF: Widget for triggering retrieve of all studies with detected differences #2977 
- [ ] UI Navigation DIFF: Widget to export a particular study #3005 
- [ ] UI Navigation DIFF: Widget for triggering export of all studies with detected differences #3006 
- [ ] UI Navigation DIFF: Widget to reject particular study #3014 l
- [ ] UI Navigation DIFF: Widget to reject all studies with detected differences #3015 
- [ ] UI Navigation DIFF: Widget to delete particular study permanently #3016 
- [ ] UI Navigation DIFF: Widget to delete all studies with detected differences permanently #3017 
- [ ] UI Navigation DIFF: Widget to align patient of a particular study between compared archives #3018 
- [ ] UI Navigation DIFF: Widget to align patient of all studies between compared archives #3019 
- [ ] UI Navigation DIFF: Widget to re-import a particular study #3020 
- [ ] UI Navigation DIFF: Widget to re-import all studies with detected differences #3021 
- [ ] UI Navigation DIFF: Widget to align attributes of a particular study between compared archives #3022 
- [ ] UI Navigation DIFF: Widget to align attributes of a studies between compared archives #3023
